#!/usr/bin/env bash
# Regenerate the ADR index (README.md) from the ADR corpus.
# Repo-generic: the variant column appears only if any ADR declares one.
# Usage: adr-index.sh [adr-dir]   (default: docs/adr)
set -uo pipefail

DIR="${1:-docs/adr}"
OUT="$DIR/README.md"
[ -d "$DIR" ] || { echo "no such directory: $DIR" >&2; exit 1; }

field() {  # field <file> <key>
  sed -n '/^---$/,/^---$/p' "$1" \
    | grep -m1 "^$2:" \
    | sed "s/^$2:[[:space:]]*//; s/^[\"']//; s/[\"']$//; s/[[:space:]]*$//"
}
listval() { field "$1" "$2" | tr -d '[]' | sed 's/[[:space:]]*,[[:space:]]*/, /g'; }

tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT

shopt -s nullglob
files=("$DIR"/ADR-[0-9][0-9][0-9][0-9]-*.md)
shopt -u nullglob

for f in "${files[@]}"; do
  id=$(field "$f" id);       [ -n "$id" ]     || id=$(basename "$f" | grep -oE '^ADR-[0-9]{4}')
  title=$(field "$f" title); [ -n "$title" ]  || title='(untitled)'
  status=$(field "$f" status); [ -n "$status" ] || status='unknown'
  date=$(field "$f" date)
  var=$(listval "$f" variant);      [ -n "$var" ]  || var=$(listval "$f" odoo_version)   # legacy key
  comp=$(listval "$f" components);  [ -n "$comp" ] || comp=$(listval "$f" modules)       # legacy key
  rfc=$(field "$f" rfc)
  sup=$(field "$f" superseded_by)
  binds=$(listval "$f" affects_repos)
  for v in var comp rfc sup binds date; do [ "${!v}" = "null" ] && printf -v "$v" '%s' ""; done
  printf '%s\037%s\037%s\037%s\037%s\037%s\037%s\037%s\037%s\037%s\n' \
    "$id" "$status" "$title" "${date:-—}" "${var:-}" "${comp:-—}" "${rfc:-—}" "${sup:-}" "$(basename "$f")" "${binds:-}"
done | sort > "$tmp"

total=$(grep -c . "$tmp" || true)
count() { awk -F'\037' -v s="$1" '$2==s' "$tmp" | grep -c . || true; }
HASVAR=$(awk -F'\037' '$5!=""' "$tmp" | grep -c . || true)
HASBIND=$(awk -F'\037' '$10!=""' "$tmp" | grep -c . || true)

{
  echo "# Architecture Decision Records"
  echo
  echo "<!-- GENERATED by adr-index.sh — do not edit by hand. -->"
  echo
  echo "Format: [MADR 4.0.0](https://adr.github.io/madr/). One decision per file,"
  echo "immutable once accepted, superseded rather than edited."
  echo
  echo "**$total records** — accepted $(count accepted) · proposed $(count proposed) · superseded $(count superseded) · deprecated $(count deprecated) · rejected $(count rejected)"
  echo

  header() {
    local h="| ID | Decision | Date |" sep="|---|---|---|"
    if [ "$HASVAR" -gt 0 ]; then h="$h Variant |"; sep="$sep---|"; fi
    h="$h Components | RFC |"; sep="$sep---|---|"
    if [ "$HASBIND" -gt 0 ]; then h="$h Binds |"; sep="$sep---|"; fi
    echo "$h"; echo "$sep"
  }

  emit_table() {  # emit_table <status> <heading>
    local rows; rows=$(awk -F'\037' -v s="$1" '$2==s' "$tmp")
    [ -n "$rows" ] || return 0
    echo "## $2"; echo
    header
    printf '%s\n' "$rows" | while IFS=$'\037' read -r id st title date var comp rfc sup file binds; do
      local suffix="" row
      [ -n "$sup" ] && suffix=" → **$sup**"
      row="| [$id]($file) | $title$suffix | $date |"
      [ "$HASVAR"  -gt 0 ] && row="$row ${var:-—} |"
      row="$row $comp | $rfc |"
      [ "$HASBIND" -gt 0 ] && row="$row ${binds:-—} |"
      echo "$row"
    done
    echo
  }

  emit_table accepted "Accepted"; emit_table proposed "Proposed"
  emit_table superseded "Superseded"; emit_table deprecated "Deprecated"
  emit_table rejected "Rejected"

  echo "## By component"
  echo
  awk -F'\037' '$6!="—" && $6!="" {n=split($6,m,", "); for(i=1;i<=n;i++) if(m[i]!="") print m[i]"\t"$1}' "$tmp" \
    | sort | awk -F'\t' '{a[$1]=a[$1]" "$2} END {for (k in a) print "- **"k"** —"a[k]}' | sort
  echo
  echo "Query before proposing anything:"
  echo '```bash'
  echo "grep -l 'components:.*<component>' $DIR/*.md"
  echo '```'
} > "$OUT"

echo "$OUT regenerated — $total ADRs (accepted $(count accepted), superseded $(count superseded))"
